### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by desss1** [MewsSystems/gitbook-distributor-guide#2]
I think you have a typo in the documentation

Instead of:

http://www.yourwebsite.com/?mewsStart=2015-01-01&mewVoucherCode=special-discount&language=en-US

you should probably have:

http://www.yourwebsite.com/?mewsStart=2015-01-01&mewsVoucherCode=special-discount&language=en-US

(mewVoucherCode vs mewsVoucherCode)

doc link: https://mews-systems.gitbook.io/distributor-guide/distributor-widget/advanced-guide

**Comment by Bash2** [comment]
Yes, you are right, thanks for the report. I just submitted a fix.
